# Generated by Django 4.2.1 on 2023-06-05 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_alter_expense_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together={('name', 'user')},
        ),
    ]
